# ETAPA 1: Construcción (Usamos Maven con Java 21)
FROM maven:3.9.9-eclipse-temurin-21-alpine AS build
COPY . .
RUN mvn clean package -DskipTests

# ETAPA 2: Ejecución (Usamos Java 21 ligero para correr la app)
FROM eclipse-temurin:21-jdk-alpine
COPY --from=build /target/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]